# fly.toml app configuration file generated for comic-unity on 2023-10-10T16:35:10+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "comic-unity"
primary_region = "lhr"

[build]

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
